"""
Governed project.build capability.

Planner may only select allowlisted profile ("build").
No arbitrary commands, roots, env, or isolation overrides.

Produces a real project-scoped artifact with trusted SHA-256 digest.

When ``devos.build.json`` is present, uses the trusted content-build contract
(deterministic, no network). Otherwise attempts the existing lifecycle build
action under isolation.
"""
from __future__ import annotations

import hashlib
import json
import logging
import time
from pathlib import Path
from typing import Any, Optional

from execution.files import FileService, PathViolation
from execution.artifacts import content_hash

logger = logging.getLogger("devos.project_build")

CAP_PROJECT_BUILD = "project.build"
PROFILE_BUILD = "build"
ALLOWED_PROFILES = frozenset({PROFILE_BUILD})
BUILD_CONTRACT = "devos.build.json"
MAX_DIAG_CHARS = 2000
MAX_SOURCE_BYTES = 512_000
MAX_ARTIFACT_BYTES = 512_000


class ProjectBuildError(Exception):
    def __init__(self, code: str, message: str):
        self.code = code
        self.message = message
        super().__init__(message)


def _bound(s: str, n: int = MAX_DIAG_CHARS) -> str:
    s = str(s or "")
    return s if len(s) <= n else s[: n - 12] + "\n…[truncated]"


def _safe_project_id(raw: Any) -> str:
    s = str(raw or "").strip()
    if not s:
        raise ProjectBuildError("PROJECT_REQUIRED", "project_id required")
    if "\x00" in s or "/" in s or "\\" in s or ".." in s or s in (".", ".."):
        raise ProjectBuildError("INVALID_PROJECT", f"invalid project_id: {s!r}")
    if len(s) > 64:
        raise ProjectBuildError("INVALID_PROJECT", "project_id too long")
    return s


def _profile(raw: Any) -> str:
    p = str(raw or "").strip().lower()
    if not p:
        raise ProjectBuildError("PROFILE_REQUIRED", "profile required")
    if p not in ALLOWED_PROFILES:
        raise ProjectBuildError("UNSUPPORTED_PROFILE", f"unsupported profile: {p!r}")
    return p


def _safe_rel(path: str, *, label: str = "path") -> str:
    raw = str(path or "").replace("\\", "/").strip().lstrip("/")
    if not raw:
        raise ProjectBuildError("PATH_REQUIRED", f"{label} required")
    if "\x00" in raw:
        raise ProjectBuildError("PATH_NULL", f"null byte in {label}")
    if raw.startswith("/") or (len(raw) > 1 and raw[1] == ":"):
        raise ProjectBuildError("PATH_ABSOLUTE", f"absolute {label} refused")
    parts = [p for p in raw.split("/") if p not in ("", ".")]
    if any(p == ".." for p in parts):
        raise ProjectBuildError("PATH_TRAVERSAL", f"traversal in {label} refused")
    if len(parts) > 12:
        raise ProjectBuildError("PATH_DEPTH", f"{label} too deep")
    return "/".join(parts)


def _load_build_contract(fs: FileService) -> Optional[dict]:
    try:
        p = fs._resolve(BUILD_CONTRACT)
    except PathViolation:
        return None
    if not p.is_file():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:
        raise ProjectBuildError("INVALID_CONTRACT", f"invalid {BUILD_CONTRACT}: {e}") from e
    if not isinstance(data, dict):
        raise ProjectBuildError("INVALID_CONTRACT", f"{BUILD_CONTRACT} must be object")
    return data


def _content_build(fs: FileService, contract: dict) -> dict:
    """Trusted deterministic build from devos.build.json (no process execution)."""
    artifact_rel = _safe_rel(contract.get("artifact") or "dist/app.js", label="artifact")
    sources = contract.get("sources") or ["src/calculator.js"]
    if not isinstance(sources, list) or not sources:
        raise ProjectBuildError("INVALID_CONTRACT", "sources required")
    if len(sources) > 20:
        raise ProjectBuildError("INVALID_CONTRACT", "too many sources")

    parts: list[str] = []
    parts.append("// generated by DevOS project.build (content contract)\n")
    parts.append(f"// profile={PROFILE_BUILD}\n")
    for src in sources:
        rel = _safe_rel(str(src), label="source")
        try:
            sp = fs._resolve(rel)
        except PathViolation as e:
            raise ProjectBuildError("PATH_VIOLATION", str(e)) from e
        if not sp.is_file():
            raise ProjectBuildError("SOURCE_MISSING", f"missing source: {rel}")
        data = sp.read_bytes()
        if len(data) > MAX_SOURCE_BYTES:
            raise ProjectBuildError("SOURCE_TOO_LARGE", f"source too large: {rel}")
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as e:
            raise ProjectBuildError("SOURCE_BINARY", f"binary source unsupported: {rel}") from e
        parts.append(f"\n// ---- source: {rel} ----\n")
        parts.append(text)
        if not text.endswith("\n"):
            parts.append("\n")

    # Require a marker that broken sources fail (optional contract field)
    require_contains = contract.get("require_contains")
    forbid_contains = contract.get("forbid_contains")
    body = "".join(parts)
    if require_contains is not None and str(require_contains) not in body:
        raise ProjectBuildError(
            "BUILD_FAILED",
            f"source does not satisfy require_contains={require_contains!r}",
        )
    if forbid_contains is not None and str(forbid_contains) in body:
        raise ProjectBuildError(
            "BUILD_FAILED",
            f"source contains forbid_contains={forbid_contains!r}",
        )

    out_bytes = body.encode("utf-8")
    if len(out_bytes) > MAX_ARTIFACT_BYTES:
        raise ProjectBuildError("ARTIFACT_TOO_LARGE", "artifact exceeds limit")

    try:
        ap = fs._resolve(artifact_rel)
    except PathViolation as e:
        raise ProjectBuildError("PATH_VIOLATION", str(e)) from e
    ap.parent.mkdir(parents=True, exist_ok=True)
    try:
        ap.parent.resolve().relative_to(fs.root)
    except ValueError as e:
        raise ProjectBuildError("PATH_VIOLATION", "artifact parent escapes workspace") from e
    ap.write_bytes(out_bytes)
    digest = content_hash(out_bytes)
    size = len(out_bytes)
    return {
        "success": True,
        "status": "succeeded",
        "profile": PROFILE_BUILD,
        "artifact": {
            "path": artifact_rel,
            "size": size,
            "digest": digest,
        },
        "diagnostics": {
            "summary": f"built {artifact_rel} ({size} bytes)",
            "mode": "content_contract",
            "sources": [str(s) for s in sources],
        },
        "isolation": {
            "required": False,
            "actual": "none_required",
            "policy": "content_build",
        },
        "exit_code": 0,
    }


async def _lifecycle_build(user_id: str, project_id: str) -> dict:
    from execution.runtime_service import run_lifecycle_action
    from execution.app_runtime import AppRuntimeState

    t0 = time.perf_counter()
    try:
        snap = await run_lifecycle_action(user_id, project_id, "build")
    except ValueError as e:
        raise ProjectBuildError("INVALID_ACTION", str(e)) from e
    except Exception as e:
        raise ProjectBuildError("RUNTIME_ERROR", f"{type(e).__name__}:{e}") from e
    duration_ms = int((time.perf_counter() - t0) * 1000)
    state = str(snap.state or "")
    evidence = dict(snap.evidence or {})
    exit_code = evidence.get("exit_code")
    if exit_code is None:
        exit_code = 0 if state in ("READY", "BUILT", "ready", "built") else 1
    success = int(exit_code) == 0 and state not in ("FAILED", "failed", "UNSUPPORTED", "unsupported")
    isolation = evidence.get("isolation") or {
        "required": True,
        "actual": evidence.get("isolation_mode") or "runtime_managed",
        "policy": "untrusted",
    }
    return {
        "success": bool(success),
        "status": "succeeded" if success else "failed",
        "profile": PROFILE_BUILD,
        "artifact": None,
        "diagnostics": {
            "summary": _bound(snap.detail or ("build ok" if success else "build failed")),
            "state": state,
            "log_tail": _bound(snap.logs_tail or "", 1500),
            "mode": "runtime_build",
        },
        "isolation": isolation if isinstance(isolation, dict) else {"actual": str(isolation)},
        "exit_code": int(exit_code),
        "duration_ms": duration_ms,
    }


async def execute_project_build(contract, req) -> dict:
    inputs = dict(req.inputs or {})
    for banned in (
        "command", "shell", "executable", "argv", "cwd", "workspace_root",
        "environment", "env", "docker_args", "host_path", "isolation",
        "owner_id", "tenant_id", "project_id", "output", "output_path",
        "success", "verified", "artifact_digest", "digest", "evidence",
    ):
        if banned in inputs:
            raise ProjectBuildError("FORBIDDEN_FIELD", f"planner cannot supply {banned}")

    ctx = req.context
    owner = str(getattr(ctx, "owner_id", "") or "").strip()
    if not owner:
        raise ProjectBuildError("OWNER_REQUIRED", "owner_id required")
    meta = dict(getattr(ctx, "metadata", None) or {})
    project_id = _safe_project_id(meta.get("project_id"))
    profile = _profile(inputs.get("profile"))

    fs = FileService(owner, project_id)
    t0 = time.perf_counter()

    build_contract = _load_build_contract(fs)
    if build_contract is not None:
        # Contract profile must match when specified
        cprof = str(build_contract.get("profile") or PROFILE_BUILD).strip().lower()
        if cprof != profile:
            raise ProjectBuildError("PROFILE_MISMATCH", f"contract profile {cprof!r} != {profile!r}")
        try:
            result = _content_build(fs, build_contract)
        except ProjectBuildError:
            raise
        except Exception as e:
            raise ProjectBuildError("BUILD_FAILED", f"{type(e).__name__}:{e}") from e
    else:
        result = await _lifecycle_build(owner, project_id)

    duration_ms = result.get("duration_ms")
    if duration_ms is None:
        duration_ms = int((time.perf_counter() - t0) * 1000)

    artifact = result.get("artifact")
    # Independently re-hash artifact when present
    if isinstance(artifact, dict) and artifact.get("path"):
        try:
            ap = fs._resolve(str(artifact["path"]))
            if ap.is_file():
                data = ap.read_bytes()
                artifact = {
                    "path": str(artifact["path"]),
                    "size": len(data),
                    "digest": content_hash(data),
                }
        except Exception:
            pass

    evidence_body = {
        "kind": CAP_PROJECT_BUILD,
        "profile": profile,
        "project_id": project_id,
        "owner_id": owner,
        "success": bool(result.get("success")),
        "status": result.get("status"),
        "exit_code": result.get("exit_code"),
        "isolation": result.get("isolation"),
        "artifact": artifact,
    }
    # Evidence digest excludes nested self-reference
    evid_hash = hashlib.sha256(
        json.dumps(evidence_body, sort_keys=True, default=str).encode()
    ).hexdigest()
    evidence_body["digest"] = evid_hash

    return {
        "success": bool(result.get("success")),
        "status": result.get("status"),
        "profile": profile,
        "project_id": project_id,
        "artifact": artifact,
        "diagnostics": result.get("diagnostics") or {},
        "exit_code": result.get("exit_code"),
        "duration_ms": duration_ms,
        "isolation": result.get("isolation"),
        "evidence": evidence_body,
        "evidence_digest": evid_hash,
    }


def _make_executor():
    async def _exec(contract, req):
        try:
            return await execute_project_build(contract, req)
        except ProjectBuildError as e:
            raise RuntimeError(f"{e.code}:{e.message}") from e
        except PathViolation as e:
            raise RuntimeError(f"PATH_VIOLATION:{e}") from e

    return _exec


def ensure_project_build_registered() -> None:
    from governance.capability_substrate import get_capability_substrate
    from governance.capability_catalog import (
        CapabilityCatalogEntry,
        catalog_register_entry_for_tests,
    )

    sub = get_capability_substrate()
    sub.register_executor(CAP_PROJECT_BUILD, _make_executor())

    schema = {
        "type": "object",
        "required": ["profile"],
        "properties": {
            "profile": {
                "type": "string",
                "description": "Allowlisted build profile: build",
            },
        },
        "additionalProperties": False,
    }
    catalog_register_entry_for_tests(
        CapabilityCatalogEntry(
            capability_id=CAP_PROJECT_BUILD,
            display_name="Project Build",
            description="Governed project build (profile-based; produces real artifact)",
            version="1",
            input_schema=schema,
            output_schema={
                "type": "object",
                "required": ["success", "status", "profile"],
                "properties": {
                    "success": {"type": "boolean"},
                    "status": {"type": "string"},
                    "artifact": {"type": "object"},
                    "evidence": {"type": "object"},
                },
            },
            risk_class="write",
            consequential=True,
            requires_authorization=True,
            required_isolation="restricted",
            evidence_requirements={"profile": True, "artifact": True, "digest": True},
            status="active",
            category="build",
            source="project_build",
        )
    )
    try:
        from governance.capability_registry import (
            CapabilityCategory,
            CapabilityDescriptor,
            CapabilityRisk,
            get_registry,
        )

        reg = get_registry()
        if reg.get(CAP_PROJECT_BUILD) is None:
            reg.register(
                CapabilityDescriptor(
                    slug=CAP_PROJECT_BUILD,
                    name="Project Build",
                    category=CapabilityCategory.SYSTEM,
                    description="Governed project build",
                    risk=CapabilityRisk.MEDIUM,
                    trust_required="standard",
                    input_schema=schema,
                    output_schema={"type": "object"},
                    metadata={
                        "consequential": True,
                        "required_isolation": "restricted",
                        "status": "active",
                        "profiles": sorted(ALLOWED_PROFILES),
                    },
                )
            )
    except Exception as e:
        logger.debug("registry register skipped: %s", type(e).__name__)
