-- ============================================================================
-- ROLLBACK: 20260918200000_agentic_runtime_checkpoints
-- ============================================================================
-- Forward migration: supabase/migrations/20260918200000_agentic_runtime_checkpoints.sql
--
-- PURPOSE OF FORWARD MIGRATION
-- ---------------------------
-- Introduces additive table `agentic_runtime_checkpoints` as an optional
-- PostgreSQL source of truth for durable agentic runtime checkpoints
-- (state machine, turn counters, linked operation/job ids, evidence refs).
--
-- Does NOT alter existing tables (AgentTaskRecord, ExecutionOperation,
-- ExecutionJob, automation_run_records, etc.).
-- Does NOT drop or rewrite data.
-- Application remains correct using process-local / GovernedAgentTask.recovery
-- even if this table is absent.
--
-- WHAT THIS ROLLBACK REMOVES
-- --------------------------
-- 1. Unique index  uq_agentic_cp_owner_idem
--      ON (owner_id, idempotency_key) WHERE idempotency_key IS NOT NULL
-- 2. Index          idx_agentic_cp_parent_run  ON (parent_run_id)
-- 3. Index          idx_agentic_cp_state       ON (state)
-- 4. Index          idx_agentic_cp_tenant      ON (tenant_id)
-- 5. Index          idx_agentic_cp_owner       ON (owner_id)
-- 6. Table          agentic_runtime_checkpoints
--
-- DATA IMPACT
-- -----------
-- DROP TABLE destroys all rows in agentic_runtime_checkpoints.
-- Checkpoint history stored ONLY in this table will be lost.
-- Checkpoint data mirrored on GovernedAgentTask.recovery.runtime_checkpoint
-- (process/disk agent task store) is NOT deleted by this rollback.
--
-- PRECONDITIONS (run before applying this file)
-- ---------------------------------------------
-- 1. Application code that SELECTs/INSERTs agentic_runtime_checkpoints has been
--    rolled back to a revision that does not require the table, OR is known to
--    treat the table as optional (best-effort persist).
-- 2. No external reporting/ETL depends exclusively on this table.
-- 3. Optional: export remaining rows for forensics:
--
--      COPY (
--        SELECT * FROM agentic_runtime_checkpoints
--      ) TO '/tmp/agentic_runtime_checkpoints_backup.csv' WITH CSV HEADER;
--
--      -- or JSON:
--      -- SELECT json_agg(t) FROM agentic_runtime_checkpoints t;
--

-- PRE-ROLLBACK DATA VERIFICATION (run these queries first; do not skip)
-- --------------------------------------------------------------------
-- Goal: understand impact before DROP TABLE destroys rows.
-- Exit if any check indicates an active dependency you still need.
--
-- V1. Table exists?
--     SELECT to_regclass('public.agentic_runtime_checkpoints') AS reg;
--     -- NULL  → nothing to roll back; still safe to run this script (IF EXISTS).
--     -- non-NULL → continue V2–V6.
--
-- V2. Row counts and state distribution
--     SELECT COUNT(*) AS total_rows FROM agentic_runtime_checkpoints;
--     SELECT state, COUNT(*) AS n
--       FROM agentic_runtime_checkpoints
--      GROUP BY state
--      ORDER BY n DESC;
--
-- V3. In-flight / non-terminal work that would be lost
--     SELECT task_id, owner_id, tenant_id, state, turn, operation_id, job_id, updated_at
--       FROM agentic_runtime_checkpoints
--      WHERE state NOT IN ('completed', 'failed', 'cancelled')
--      ORDER BY updated_at DESC
--      LIMIT 100;
--     -- If this returns rows, pause: those tasks may still be recoverable from
--     -- this table. Prefer draining or exporting before DROP.
--
-- V4. UNKNOWN / BLOCKED rows (must not be silently discarded without review)
--     SELECT task_id, owner_id, state, failure, unknown_info, updated_at
--       FROM agentic_runtime_checkpoints
--      WHERE state IN ('unknown', 'blocked')
--      ORDER BY updated_at DESC
--      LIMIT 100;
--
-- V5. Cross-check linked operations still exist (optional; requires ops table)
--     SELECT c.task_id, c.operation_id, c.state AS cp_state
--       FROM agentic_runtime_checkpoints c
--      WHERE c.operation_id IS NOT NULL
--        AND c.state IN ('executing', 'unknown', 'observing')
--      LIMIT 50;
--     -- Manually join/inspect execution_operations if present in your schema.
--
-- V6. Tenant/owner footprint (isolation audit sample)
--     SELECT owner_id, tenant_id, COUNT(*) AS n
--       FROM agentic_runtime_checkpoints
--      GROUP BY owner_id, tenant_id
--      ORDER BY n DESC
--      LIMIT 50;
--
-- V7. Optional full export before DROP (recommended if V2 total_rows > 0)
--     COPY (
--       SELECT * FROM agentic_runtime_checkpoints
--     ) TO '/tmp/agentic_runtime_checkpoints_backup.csv' WITH CSV HEADER;
--
--     -- Verify export non-empty when table had rows:
--     --   wc -l /tmp/agentic_runtime_checkpoints_backup.csv
--
-- PASS CRITERIA TO PROCEED WITH DROP
-- ----------------------------------
-- [ ] V1 understood (table missing or present)
-- [ ] V2 reviewed (no unexpected row volume)
-- [ ] V3 empty OR operator explicitly accepts loss of in-flight checkpoints
-- [ ] V4 reviewed (UNKNOWN/BLOCKED exported or accepted)
-- [ ] V7 backup taken if total_rows > 0 and data may be needed
-- [ ] Application revision does not hard-require this table
--
-- HOW TO APPLY ROLLBACK
-- ---------------------
-- psql "$DATABASE_URL" -v ON_ERROR_STOP=1 \
--   -f supabase/migrations/20260918200000_agentic_runtime_checkpoints.down.sql
--
-- Or via Supabase CLI if your pipeline supports explicit down files:
--   supabase db execute -f supabase/migrations/20260918200000_agentic_runtime_checkpoints.down.sql
--
-- ORDER MATTERS
-- -------------
-- Drop dependent indexes first, then the table. IF EXISTS keeps the script
-- idempotent if partially applied or already rolled back.
--
-- IRREVERSIBILITY
-- ---------------
-- Schema can be re-created by re-running the forward migration.
-- Row data dropped by this script is not recovered unless a backup was taken.
-- That is intentional for an additive optional table; no other DevOS tables
-- are modified.
--
-- VERIFICATION AFTER ROLLBACK
-- ---------------------------
--   SELECT to_regclass('public.agentic_runtime_checkpoints');  -- expect NULL
--   -- Existing agentic / automation / execution tables must still exist:
--   SELECT to_regclass('public.execution_operations');
--   SELECT to_regclass('public.execution_jobs');
--
-- ============================================================================

DROP INDEX IF EXISTS uq_agentic_cp_owner_idem;
DROP INDEX IF EXISTS idx_agentic_cp_parent_run;
DROP INDEX IF EXISTS idx_agentic_cp_state;
DROP INDEX IF EXISTS idx_agentic_cp_tenant;
DROP INDEX IF EXISTS idx_agentic_cp_owner;
DROP TABLE IF EXISTS agentic_runtime_checkpoints;
